site_name: My projects
site_author: Kmail Semczuk
site_description: >
  DataCraft â€“ Engineering, Science & AI, Analytics projects

site_url: https://KamilSemczuk13/ds_portfolio_ENG
repo_name: KamilSemczuk13/ds_portfolio
repo_url: https://github.com/KamilSemczuk13/ds_portfolio_ENG.git

theme:
  name: material

nav:
  - ğŸ  Start: index.md
  - âš™ï¸ Data Engeneering:
    - ğŸšš KPI Pipeline: Data_Engineering\KPI_Pipeline\index.md
    - ğŸ›’ Shop Data Explorer: Data_Engineering/Shop/index.md
  - ğŸ¤– Data Science & AI:
    - ğŸƒâ€â™‚ï¸ Halfmaraton: Data_Science/Maraton/index.md
    - âœˆï¸ Flight4u â€“ flight searching: Data_Science/Loty/index.md
  - ğŸ“Š Data Analysis:
    - ğŸ›³ï¸ Titanic (survivival analysis): Data_Analysis/Titanic/index.md
    - ğŸŒ¸ Iris (classyfication of Irises): Data_Analysis/Iris/index.md
  # - ğŸ“Š Analysis:    
  #    - ğŸ›³ï¸ Titanic (survivival analysis): Analizy/Titanic/index.md
  #    - ğŸŒ¸ Iris (classyfication of Irises): Analizy/Iris/index.md
  # - ğŸ’» Apps: 
  #     - ğŸƒâ€â™‚ï¸ Halfmaraton: Aplikacje/Maraton/index.md
  #     - âœˆï¸ Flight4u â€“ flight searching: Aplikacje/Loty/index.md

#- ğŸŸ¢ Obecny projekt: - ğŸ”™ Poprzednie projekty:


