site_name: My projects
site_author: Kmail Semczuk
site_description: >
  Portfolio of my Data Science and AI projects!

site_url: https://KamilSemczuk13/ds_portfolio_ENG
repo_name: KamilSemczuk13/ds_portfolio
repo_url: https://github.com/KamilSemczuk13/ds_portfolio_ENG.git

theme:
  name: material

nav:
  - ğŸ  Start: index.md
  - ğŸ“Š Analysis:    
     - ğŸ›³ï¸ Titanic (survivival analysis): Analizy/Titanic/index.md
     - ğŸŒ¸ Iris (classyfication of Irises): Analizy/Iris/index.md
  - ğŸ’» Apps: 
      - ğŸƒâ€â™‚ï¸ Halfmaraton: Aplikacje/Maraton/index.md
      - âœˆï¸ Flight4u â€“ flight searching: Aplikacje/Loty/index.md

#- ğŸŸ¢ Obecny projekt: - ğŸ”™ Poprzednie projekty:


